@startuml
title CTAP

node "Platform(Windows10,Android,Mac,iOS)" {
    frame "Browser(Chrome,Edge,Firefox,Safari?)" {
        package "UserProgram(JS)" {
            component "WebAuthn\n - navigator.credentials.create()\n - navigator.credentials.get()" as WebAuthn
        }
    }
}   

component "FIDO2 Authenticator(USB)" as FIDOKeyUSB
component "FIDO2 Authenticator(NFC)" as FIDOKeyNFC
component "FIDO2 Authenticator(BLE)" as FIDOKeyBLE

WebAuthn ..> FIDOKeyUSB:**CTAP** \n**USB Protocol**
WebAuthn ..> FIDOKeyNFC:**CTAP** \n**NFC Protocol**
WebAuthn ..> FIDOKeyBLE:**CTAP** \n**BLE Protocol**

@enduml